//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEL_ONE.ReceptorInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="FEL", ConfigurationName="ReceptorInfo.ReceptorInfoSoapPort")]
    public interface ReceptorInfoSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (ReceptorInfo.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="FELaction/ARECEPTORINFO.Execute", ReplyAction="*")]
        FEL_ONE.ReceptorInfo.ExecuteResponse Execute(FEL_ONE.ReceptorInfo.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="FELaction/ARECEPTORINFO.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<FEL_ONE.ReceptorInfo.ExecuteResponse> ExecuteAsync(FEL_ONE.ReceptorInfo.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceptorInfo.Execute", WrapperNamespace="FEL", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=0)]
        public string Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=1)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=2)]
        public string Clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=3)]
        public string Receptorid;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Cliente, string Usuario, string Clave, string Receptorid) {
            this.Cliente = Cliente;
            this.Usuario = Usuario;
            this.Clave = Clave;
            this.Receptorid = Receptorid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceptorInfo.ExecuteResponse", WrapperNamespace="FEL", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=0)]
        public string Informacion;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Informacion) {
            this.Informacion = Informacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceptorInfoSoapPortChannel : FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptorInfoSoapPortClient : System.ServiceModel.ClientBase<FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort>, FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort {
        
        public ReceptorInfoSoapPortClient() {
        }
        
        public ReceptorInfoSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptorInfoSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorInfoSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorInfoSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FEL_ONE.ReceptorInfo.ExecuteResponse FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort.Execute(FEL_ONE.ReceptorInfo.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string Cliente, string Usuario, string Clave, string Receptorid) {
            FEL_ONE.ReceptorInfo.ExecuteRequest inValue = new FEL_ONE.ReceptorInfo.ExecuteRequest();
            inValue.Cliente = Cliente;
            inValue.Usuario = Usuario;
            inValue.Clave = Clave;
            inValue.Receptorid = Receptorid;
            FEL_ONE.ReceptorInfo.ExecuteResponse retVal = ((FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort)(this)).Execute(inValue);
            return retVal.Informacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FEL_ONE.ReceptorInfo.ExecuteResponse> FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort.ExecuteAsync(FEL_ONE.ReceptorInfo.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FEL_ONE.ReceptorInfo.ExecuteResponse> ExecuteAsync(string Cliente, string Usuario, string Clave, string Receptorid) {
            FEL_ONE.ReceptorInfo.ExecuteRequest inValue = new FEL_ONE.ReceptorInfo.ExecuteRequest();
            inValue.Cliente = Cliente;
            inValue.Usuario = Usuario;
            inValue.Clave = Clave;
            inValue.Receptorid = Receptorid;
            return ((FEL_ONE.ReceptorInfo.ReceptorInfoSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
