//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEL_ONE.Guatefacturas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dbguatefac/Guatefac.wsdl", ConfigurationName="Guatefacturas.Guatefac")]
    public interface Guatefac {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dbguatefac/Guatefac.wsdl/anulaDocumento", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string anulaDocumento(string pUsuario, string pPassword, string pNitEmisor, string pSerie, string pPreimpreso, string pNitComprador, string pFechaAnulacion, string pMotivoAnulacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dbguatefac/Guatefac.wsdl/anulaDocumento", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> anulaDocumentoAsync(string pUsuario, string pPassword, string pNitEmisor, string pSerie, string pPreimpreso, string pNitComprador, string pFechaAnulacion, string pMotivoAnulacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dbguatefac/Guatefac.wsdl/generaDocumento", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string generaDocumento(string pUsuario, string pPassword, string pNitEmisor, decimal pEstablecimiento, decimal pTipoDoc, string pIdMaquina, string pTipoRespuesta, string pXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dbguatefac/Guatefac.wsdl/generaDocumento", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> generaDocumentoAsync(string pUsuario, string pPassword, string pNitEmisor, decimal pEstablecimiento, decimal pTipoDoc, string pIdMaquina, string pTipoRespuesta, string pXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GuatefacChannel : FEL_ONE.Guatefacturas.Guatefac, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuatefacClient : System.ServiceModel.ClientBase<FEL_ONE.Guatefacturas.Guatefac>, FEL_ONE.Guatefacturas.Guatefac {
        
        public GuatefacClient() {
        }
        
        public GuatefacClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuatefacClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuatefacClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuatefacClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string anulaDocumento(string pUsuario, string pPassword, string pNitEmisor, string pSerie, string pPreimpreso, string pNitComprador, string pFechaAnulacion, string pMotivoAnulacion) {
            return base.Channel.anulaDocumento(pUsuario, pPassword, pNitEmisor, pSerie, pPreimpreso, pNitComprador, pFechaAnulacion, pMotivoAnulacion);
        }
        
        public System.Threading.Tasks.Task<string> anulaDocumentoAsync(string pUsuario, string pPassword, string pNitEmisor, string pSerie, string pPreimpreso, string pNitComprador, string pFechaAnulacion, string pMotivoAnulacion) {
            return base.Channel.anulaDocumentoAsync(pUsuario, pPassword, pNitEmisor, pSerie, pPreimpreso, pNitComprador, pFechaAnulacion, pMotivoAnulacion);
        }
        
        public string generaDocumento(string pUsuario, string pPassword, string pNitEmisor, decimal pEstablecimiento, decimal pTipoDoc, string pIdMaquina, string pTipoRespuesta, string pXml) {
            return base.Channel.generaDocumento(pUsuario, pPassword, pNitEmisor, pEstablecimiento, pTipoDoc, pIdMaquina, pTipoRespuesta, pXml);
        }
        
        public System.Threading.Tasks.Task<string> generaDocumentoAsync(string pUsuario, string pPassword, string pNitEmisor, decimal pEstablecimiento, decimal pTipoDoc, string pIdMaquina, string pTipoRespuesta, string pXml) {
            return base.Channel.generaDocumentoAsync(pUsuario, pPassword, pNitEmisor, pEstablecimiento, pTipoDoc, pIdMaquina, pTipoRespuesta, pXml);
        }
    }
}
