//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEL_ONE.AnulacionTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="FEL", ConfigurationName="AnulacionTest.AnulacionSoapPort")]
    public interface AnulacionSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (Anulacion.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="FELaction/AANULACION.Execute", ReplyAction="*")]
        FEL_ONE.AnulacionTest.ExecuteResponse Execute(FEL_ONE.AnulacionTest.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="FELaction/AANULACION.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<FEL_ONE.AnulacionTest.ExecuteResponse> ExecuteAsync(FEL_ONE.AnulacionTest.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Anulacion.Execute", WrapperNamespace="FEL", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=0)]
        public string Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=1)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=2)]
        public string Clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=3)]
        public string Nitemisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=4)]
        public string Numautorizacionuuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=5)]
        public string Motivoanulacion;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Cliente, string Usuario, string Clave, string Nitemisor, string Numautorizacionuuid, string Motivoanulacion) {
            this.Cliente = Cliente;
            this.Usuario = Usuario;
            this.Clave = Clave;
            this.Nitemisor = Nitemisor;
            this.Numautorizacionuuid = Numautorizacionuuid;
            this.Motivoanulacion = Motivoanulacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Anulacion.ExecuteResponse", WrapperNamespace="FEL", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FEL", Order=0)]
        public string Respuesta;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Respuesta) {
            this.Respuesta = Respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnulacionSoapPortChannel : FEL_ONE.AnulacionTest.AnulacionSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnulacionSoapPortClient : System.ServiceModel.ClientBase<FEL_ONE.AnulacionTest.AnulacionSoapPort>, FEL_ONE.AnulacionTest.AnulacionSoapPort {
        
        public AnulacionSoapPortClient() {
        }
        
        public AnulacionSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnulacionSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnulacionSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnulacionSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FEL_ONE.AnulacionTest.ExecuteResponse FEL_ONE.AnulacionTest.AnulacionSoapPort.Execute(FEL_ONE.AnulacionTest.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string Cliente, string Usuario, string Clave, string Nitemisor, string Numautorizacionuuid, string Motivoanulacion) {
            FEL_ONE.AnulacionTest.ExecuteRequest inValue = new FEL_ONE.AnulacionTest.ExecuteRequest();
            inValue.Cliente = Cliente;
            inValue.Usuario = Usuario;
            inValue.Clave = Clave;
            inValue.Nitemisor = Nitemisor;
            inValue.Numautorizacionuuid = Numautorizacionuuid;
            inValue.Motivoanulacion = Motivoanulacion;
            FEL_ONE.AnulacionTest.ExecuteResponse retVal = ((FEL_ONE.AnulacionTest.AnulacionSoapPort)(this)).Execute(inValue);
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FEL_ONE.AnulacionTest.ExecuteResponse> FEL_ONE.AnulacionTest.AnulacionSoapPort.ExecuteAsync(FEL_ONE.AnulacionTest.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FEL_ONE.AnulacionTest.ExecuteResponse> ExecuteAsync(string Cliente, string Usuario, string Clave, string Nitemisor, string Numautorizacionuuid, string Motivoanulacion) {
            FEL_ONE.AnulacionTest.ExecuteRequest inValue = new FEL_ONE.AnulacionTest.ExecuteRequest();
            inValue.Cliente = Cliente;
            inValue.Usuario = Usuario;
            inValue.Clave = Clave;
            inValue.Nitemisor = Nitemisor;
            inValue.Numautorizacionuuid = Numautorizacionuuid;
            inValue.Motivoanulacion = Motivoanulacion;
            return ((FEL_ONE.AnulacionTest.AnulacionSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
